# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Crowsa Documentation
theme:
  name: material
  logo: assets/crowsa.svg
  favicon: assets/logo.png
  palette:
    primary: red
    accent: deep purple
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_name: Codeberg/XDR/Crowsa
repo_url: https://codeberg.org/XDR/Crowsa
copyright: Copyright &copy; 2024 XDR
